src/api/__init__.py
from src.api.server import init_app, run_app

src/api/controllers/__init__.py
from .home_page import home_page
from .volume_controller import volume_controller

src/api/controllers/home_page.py
from flask import Blueprint, render_template

home_page = Blueprint('home_page', __name__)


@home_page.route('/')
def index():
    return render_template('index.html')

src/api/controllers/volume_controller.py
from flask import Blueprint, render_template, redirect, url_for, request
import osascript

volume_controller = Blueprint(
    'volume_controller', __name__, url_prefix='/volume')


@volume_controller.route('/', methods=['GET'])
def index():
    code, out, err = osascript.run("output volume of (get volume settings)")
    if err:
        render_template('error.html', err)
    return render_template('volume/index.html', volume=out)


@volume_controller.route('/update', methods=['POST'])
def update_volume():
    new_volume = request.form.get('volume')
    code, out, err = osascript.run(f"set volume output volume {new_volume}")
    if err:
        render_template('error.html', err)
    return redirect(url_for('volume_controller.index'))

src/api/templates/base.html
<!DOCTYPE html>
<html>

<head>
  <meta charset="UTF-8" />
  <meta name="viewport" content="width=device-width, initial-scale=1.0" />
  <script src="https://cdn.tailwindcss.com"></script>
  <link href="https://cdnjs.cloudflare.com/ajax/libs/flowbite/2.1.1/flowbite.min.css" rel="stylesheet" />

  <title>{% block title %}{% endblock %} - My Webpage</title>
</head>

<body>
  {% include 'navbar.html' %}

  {% block content %}{% endblock %}

  {% include 'footer.html' %}

  <script src="https://unpkg.com/htmx.org@1.9.8"
    integrity="sha384-rgjA7mptc2ETQqXoYC3/zJvkU7K/aP44Y+z7xQuJiVnB/422P/Ak+F/AqFR7E4Wr"
    crossorigin="anonymous"></script>
  <script src="https://cdnjs.cloudflare.com/ajax/libs/flowbite/2.1.1/flowbite.min.js"></script>
  <script>
    initFlowbite();
  </script>
</body>


</html>

src/api/templates/footer.html
<footer
  class="fixed bottom-0 left-0 z-20 w-full p-4 bg-white border-t border-gray-200 shadow md:flex md:items-center md:justify-between md:p-6 dark:bg-gray-800 dark:border-gray-600">
  <div class="w-full mx-auto max-w-screen-xl p-4 md:flex md:items-center md:justify-between">
    <span class="text-sm text-gray-500 sm:text-center dark:text-gray-400">© 2023 <a
        href="https://www.github.com/joaodobread" class="hover:underline">MacController</a>. All Rights Reserved.
    </span>
  </div>
</footer>

src/api/templates/index.html
{% extends 'base.html' %}

{% block title %}
MacController
{% endblock %}

{% block content %}
<div class="m-2">
  <h1>MacController</h1>
  <p>MacController</p>
</div>
{% endblock %}

src/api/templates/navbar.html
<nav class="bg-white border-gray-200 dark:bg-gray-900">
  <div class="max-w-screen-xl flex flex-wrap items-center justify-between mx-auto p-4">
    <div class="flex items-center space-x-3 rtl:space-x-reverse">
      <a href="{{url_for('home_page.index')}}"
        class="self-center text-2xl font-semibold whitespace-nowrap dark:text-white">Home</a>
    </div>
    <button data-collapse-toggle="navbar-default" type="button"
      class="inline-flex items-center p-2 w-10 h-10 justify-center text-sm text-gray-500 rounded-lg md:hidden hover:bg-gray-100 focus:outline-none focus:ring-2 focus:ring-gray-200 dark:text-gray-400 dark:hover:bg-gray-700 dark:focus:ring-gray-600"
      aria-controls="navbar-default" aria-expanded="false">
      <span class="sr-only">Open</span>
      <svg class="w-5 h-5" aria-hidden="true" xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 17 14">
        <path stroke="currentColor" stroke-linecap="round" stroke-linejoin="round" stroke-width="2"
          d="M1 1h15M1 7h15M1 13h15" />
      </svg>
    </button>
    <div class="hidden w-full md:block md:w-auto" id="navbar-default">
      <ul
        class="font-medium flex flex-col p-4 md:p-0 mt-4 border border-gray-100 rounded-lg bg-gray-50 md:flex-row md:space-x-8 rtl:space-x-reverse md:mt-0 md:border-0 md:bg-white dark:bg-gray-800 md:dark:bg-gray-900 dark:border-gray-700">
        <li>
          <a href="{{url_for('volume_controller.index')}}"
            class="block py-2 px-3 text-white bg-blue-700 rounded md:bg-transparent md:text-blue-700 md:p-0 dark:text-white md:dark:text-blue-500"
            aria-current="page">Volume Controller</a>
        </li>
      </ul>
    </div>
  </div>
</nav>

src/api/templates/volume/forms/change-volume-form.html
<form method="post" action="{{url_for('volume_controller.update_volume')}}" class="m-10">
  <div class="mb-6">
    <label for="default-range" class="block mb-2 text-sm font-medium text-gray-900 ">
      Volume <span
        class="bg-blue-100 text-blue-800 text-xs font-medium me-2 px-2.5 py-0.5 rounded dark:bg-blue-900 dark:text-blue-300"
        id="current_volume">{{volume}}%</span>
    </label>
    <input id="default-range" type="range" value="{{volume}}" min="0" max="100"
      class="w-full h-2 bg-gray-200 rounded-lg appearance-none cursor-pointer" name="volume">
  </div>
  <div class="mb-6">
    <button
      class="text-white bg-blue-700 hover:bg-blue-800 focus:ring-4 focus:ring-blue-300 font-medium rounded-lg text-sm px-5 py-2.5 me-2 mb-2 dark:bg-blue-600 dark:hover:bg-blue-700 focus:outline-none dark:focus:ring-blue-800"
      type="submit">Salvar</button>
  </div>
</form>


<script>
  (() => {
    const element = document.getElementById('default-range')
    const current_volume = document.getElementById('current_volume')
    element.addEventListener('change', () => {
      current_volume.innerText = `${element.value}%`
    })
  })()
</script>

src/api/templates/volume/index.html
{% extends 'base.html' %}


{% block title %}
MacController
{% endblock %}

{% block content %}

{% include 'volume/forms/change-volume-form.html' %}

{% endblock %}